#!/bin/bash

recipient="your-email@example.com"
telegram_bot_token="your-telegram-bot-token"
telegram_chat_id="your-telegram-chat-id"

# Initialize power status
power_status_old=$(upsc ups@localhost ups.status)

while true; do
    # Check battery charge level
    battery_charge=$(upsc ups@localhost battery.charge)
    
    # Check current power status
    power_status_new=$(upsc ups@localhost ups.status)

    # If power status has changed, send an email
    if [ "$power_status_old" != "$power_status_new" ]; then
        if echo "$power_status_new" | grep -q "OB"; then
            subject="UPS Alert: Power Loss"
            content="Power lost. UPS running on battery."
        elif echo "$power_status_new" | grep -q "OL"; then
            subject="UPS Alert: Power Restored"
            content="Power restored. UPS running on line."
        fi
        echo -e "Subject: $subject\n\n$content" | msmtp --file=/etc/msmtprc $recipient

        # Send a Telegram notification
        curl -s -X POST https://api.telegram.org/bot${telegram_bot_token}/sendMessage -d chat_id=${telegram_chat_id} -d text="$content"

        # Update power status
        power_status_old=$power_status_new
    fi

    # If battery charge is below 40%, send an email and shut down the system
    if (( battery_charge < 40 )); then
        echo "Battery charge below 40%, shutting down..."

        subject="UPS Alert: Battery Low - System Shutdown"
        content="Battery charge is below 40%. The system is shutting down."
        echo -e "Subject: $subject\n\n$content" | msmtp --file=/etc/msmtprc $recipient

        # Send a Telegram notification
        curl -s -X POST https://api.telegram.org/bot${telegram_bot_token}/sendMessage -d chat_id=${telegram_chat_id} -d text="$content"

        /sbin/shutdown -h now
        exit 0
    fi

    sleep 15
done
